### ISSUE TITLE
Open this issue back up

### ISSUE THREAD

**Issue by Ovutuleu92** [lujiangz/After-Reinstall-Windows#1]
https://github.com/lujiangz/trixware/issues/3

Open the issue ticket back up. Thats the only way we can have a chat with this stupid scammer. He's scamming everyone around and you're literally defending him. Search his shit up on google as "Sarnax Scam" or "Sarnax Github". Theres like 3 more threads like this how he scammed others. 

https://github.com/is-a-dev/register/issues/1816
https://github.community/t/i-got-scammed-by-a-developer-from-github/242944

**Comment by lujiangz** [comment]
I'm not defending anyone, I don't even know him, I just want proof from you if you're accusing someone. you can leave it here

**Comment by Ovutuleu92** [comment]
There you go mate. 
One pic where i asked him if he could make a simple ESP
One pic where i sent him the money and begged him to send me the Wallhack which he apparently already had made, as it was late and wanted to try before going to sleep.
One pic showing TXID, pic of tranny, and his Discord ID.

https://imgur.com/a/N6E0Zji

**Comment by Ovutuleu92** [comment]
He is some Thailandeese broke dog, who is scamming people for a living. He is photoshopping his "Cheats" to make it look like its an actual cheat. He literally scams everyone and denies the alligations and needs to be taken down. I can show you screenshare of my actual chat with him, how i've sent him the money, and he deleted all his messages and blocked me.

**Comment by Ovutuleu92** [comment]
Problem is he is scamming ammounts ranging from 40 USD (me) upwards to 100+. A few scams a month equals him an actual wage there in thailand. And he is not stopped yet, which is some kind of joke that this dumbass gypsy is still on github.

**Comment by Ovutuleu92** [comment]
Also, i still cant comment on the post even tho you reopened.

**Comment by Ovutuleu92** [comment]
my own thread with my story and my gathered proofs: https://github.com/Ovutuleu92/sarnaxscammerdog

**Comment by SarnaxLii** [comment]
I want to see evidence Not your words :)

**Comment by SarnaxLii** [comment]
where is my conversation I only see you talking to yourself :)

**Comment by Ovutuleu92** [comment]
@lujiangz you are fucking defending him. You didnt even check the proof i've sent, your just as much of a fucking gypsy dog as he is.

**Comment by lujiangz** [comment]
am i a github admin? What do you expect me to do ? @Ovutuleu92  and learn to be human before insulting someone

**Comment by Ovutuleu92** [comment]
> am i a github admin? What do you expect me to do ? @Ovutuleu92 and learn to be human before insulting someone
You tell me to LEARN to be a HUMAN when you are DEFENDING a SCAMMER, who stole a few grand from innocent people, you fucking male Karen.

**Comment by lujiangz** [comment]
Where am I defending it?

**Comment by Ovutuleu92** [comment]
> Where am I defending it?

he asked u to close the ting and u close it like you're his puppy on a leash lmfao

**Comment by Ovutuleu92** [comment]
Now he deleted all his replies to every fucking thread
And you're still dumb enough not to recognize hes a scammer on the loose

**Comment by lujiangz** [comment]
I don't care if he's a scammer or not because I won't take anything from him. If you didn't want him to delete things so badly, you could have taken a screenshot. Try to find a solution yourself before looking for the problem in others and don't get scammed before you say stupid words to me xd

**Comment by lujiangz** [comment]
And I also know that he's already a scammer but I don't understand why you want me to say this. Also why are you having your goddamn discussion in my repository? go find yourself another place
